# ---> Description <---
#
#  --- Add your descriptions here ---
#
# --no-install-recommends : allows you to install the specific package without any other recommendations.

FROM __________________ 
LABEL maintainer "iAmG-r00t @th3_gr00t 😀"


RUN echo "LC_ALL=en_US.UTF-8" >> /etc/environment && \
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && \
    echo "LANG=en_US.UTF-8" >> /etc/locale.conf

ARG USERNAME=user
ARG USERPASS=userpass

RUN adduser --disabled-password --gecos '' $USERNAME && \
    echo "$USERNAME:$USERPASS" | chpasswd

RUN apt-get update -y && \
    apt-get install -y vim locales locales-all && \
    rm -rf /var/lib/apt/lists/* && \
    locale-gen en_US.UTF-8